services:
  db:
    image: postgres:16
    container_name: finance_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance
    ports:
      - "5432:5432"
    volumes:
      - finance_db:/var/lib/postgresql/data

volumes:
  finance_db:
